-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "ModerationType" AS ENUM ('CROSSREPORT', 'AUTOMOD', 'STRIKE', 'MANUAL', 'APPEAL');

-- CreateEnum
CREATE TYPE "ModerationAction" AS ENUM ('WARN', 'MUTE', 'KICK', 'BAN', 'UNMUTE', 'UNBAN', 'REVOKE');

-- CreateTable
CREATE TABLE "Server"
(
	"id"               STRING NOT NULL,
	"prefix"           STRING,
	"disabledCommands" STRING[],
	"updateChannel"    STRING,
	"staffRole"        STRING,
	"adminRole"        STRING,

	CONSTRAINT "Server_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConfigValue"
(
	"guildId" STRING NOT NULL,
	"module"  STRING NOT NULL,
	"key"     STRING NOT NULL,
	"value"   STRING NOT NULL,

	CONSTRAINT "ConfigValue_pkey" PRIMARY KEY ("guildId", "module", "key")
);

-- CreateTable
CREATE TABLE "ScheduledTask"
(
	"module" STRING NOT NULL,
	"task"   STRING NOT NULL,
	"query"  STRING NOT NULL,
	"jobId"  STRING NOT NULL,

	CONSTRAINT "ScheduledTask_pkey" PRIMARY KEY ("module", "task", "query")
);

-- CreateTable
CREATE TABLE "ModerationUser"
(
	"id"           STRING NOT NULL,
	"lastKnownTag" STRING NOT NULL,

	CONSTRAINT "ModerationUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Note"
(
	"id"      INT4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"note"    STRING       NOT NULL,
	"guildId" STRING       NOT NULL,
	"date"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"userId"  STRING       NOT NULL,

	CONSTRAINT "Note_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ModerationLogItem"
(
	"id"             INT4               NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"type"           "ModerationType"   NOT NULL,
	"action"         "ModerationAction" NOT NULL,
	"moderatorId"    STRING             NOT NULL,
	"reason"         STRING             NOT NULL,
	"date"           TIMESTAMP(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"duration"       INT8,
	"strikes"        INT4,
	"strikeDate"     TIMESTAMP(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"affectedCaseId" INT4,
	"guildId"        STRING             NOT NULL,
	"offenderId"     STRING             NOT NULL,

	CONSTRAINT "ModerationLogItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Massban"
(
	"id"          INT4         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"guildId"     STRING       NOT NULL,
	"moderatorId" STRING       NOT NULL,
	"reason"      STRING       NOT NULL,
	"date"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"offenders"   STRING[],

	CONSTRAINT "Massban_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ModerationPendingLogItem"
(
	"id"             STRING             NOT NULL,
	"type"           "ModerationType"   NOT NULL,
	"action"         "ModerationAction" NOT NULL,
	"moderatorId"    STRING             NOT NULL,
	"reason"         STRING             NOT NULL,
	"duration"       INT4,
	"purgeDuration"  INT4,
	"silent"         BOOL,
	"hardMute"       BOOL,
	"strikes"        INT4,
	"guildId"        STRING             NOT NULL,
	"messageId"      STRING             NOT NULL,
	"channelId"      STRING             NOT NULL,
	"affectedCaseId" INT4,
	"offenderId"     STRING             NOT NULL,

	CONSTRAINT "ModerationPendingLogItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ModerationGuildConfig"
(
	"guildId"            STRING NOT NULL,
	"strikes"            JSONB  NOT NULL DEFAULT '[]',
	"muteRole"           STRING NOT NULL,
	"logChannel"         STRING NOT NULL,
	"publicLogChannel"   STRING,
	"strikeExpiresAfter" INT4   NOT NULL,

	CONSTRAINT "ModerationGuildConfig_pkey" PRIMARY KEY ("guildId")
);

-- CreateTable
CREATE TABLE "ActiveMute"
(
	"userId"     STRING NOT NULL,
	"guildId"    STRING NOT NULL,
	"logItemId"  INT4   NOT NULL,
	"hardMuteId" STRING,

	CONSTRAINT "ActiveMute_pkey" PRIMARY KEY ("userId", "guildId")
);

-- CreateTable
CREATE TABLE "HardMute"
(
	"id"         STRING NOT NULL,
	"knownRoles" STRING[],

	CONSTRAINT "HardMute_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TwitterShare"
(
	"id"             STRING       NOT NULL,
	"date"           TIMESTAMP(3) NOT NULL,
	"sharedByUserId" STRING       NOT NULL,

	CONSTRAINT "TwitterShare_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TwitterLeaderboardUser"
(
	"id"              STRING NOT NULL,
	"totalShares"     INT4   NOT NULL DEFAULT 0,
	"sharesThisMonth" INT4   NOT NULL DEFAULT 0,

	CONSTRAINT "TwitterLeaderboardUser_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TwitterSubscription"
(
	"handle"    STRING NOT NULL,
	"channelId" STRING NOT NULL,
	"message"   STRING,

	CONSTRAINT "TwitterSubscription_pkey" PRIMARY KEY ("handle", "channelId")
);

-- CreateTable
CREATE TABLE "TwitterBlacklist"
(
	"id" STRING NOT NULL,

	CONSTRAINT "TwitterBlacklist_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "YoutubeChannel"
(
	"id"          STRING NOT NULL,
	"name"        STRING NOT NULL,
	"englishName" STRING,
	"photo"       STRING,
	"org"         STRING,
	"subOrg"      STRING,

	CONSTRAINT "YoutubeChannel_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subscription"
(
	"id"        STRING NOT NULL,
	"message"   STRING NOT NULL,
	"channelId" STRING NOT NULL,

	CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id", "channelId")
);

-- CreateTable
CREATE TABLE "QuerySubscription"
(
	"id"              STRING NOT NULL,
	"message"         STRING NOT NULL,
	"includedOrgs"    STRING[],
	"excludedOrgs"    STRING[],
	"includedSubOrgs" STRING[],
	"excludedSubOrgs" STRING[],
	"includedVtubers" STRING[],
	"excludedVtubers" STRING[],

	CONSTRAINT "QuerySubscription_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Livestream"
(
	"id"         STRING       NOT NULL,
	"title"      STRING       NOT NULL,
	"createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"messageIds" STRING[],

	CONSTRAINT "Livestream_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ActiveMute_logItemId_key" ON "ActiveMute" ("logItemId");

-- CreateIndex
CREATE UNIQUE INDEX "ActiveMute_hardMuteId_key" ON "ActiveMute" ("hardMuteId");

-- AddForeignKey
ALTER TABLE "Note"
	ADD CONSTRAINT "Note_userId_fkey" FOREIGN KEY ("userId") REFERENCES "ModerationUser" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ModerationLogItem"
	ADD CONSTRAINT "ModerationLogItem_affectedCaseId_fkey" FOREIGN KEY ("affectedCaseId") REFERENCES "ModerationLogItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ModerationLogItem"
	ADD CONSTRAINT "ModerationLogItem_offenderId_fkey" FOREIGN KEY ("offenderId") REFERENCES "ModerationUser" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ModerationPendingLogItem"
	ADD CONSTRAINT "ModerationPendingLogItem_affectedCaseId_fkey" FOREIGN KEY ("affectedCaseId") REFERENCES "ModerationLogItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ModerationPendingLogItem"
	ADD CONSTRAINT "ModerationPendingLogItem_offenderId_fkey" FOREIGN KEY ("offenderId") REFERENCES "ModerationUser" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ActiveMute"
	ADD CONSTRAINT "ActiveMute_logItemId_fkey" FOREIGN KEY ("logItemId") REFERENCES "ModerationLogItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ActiveMute"
	ADD CONSTRAINT "ActiveMute_hardMuteId_fkey" FOREIGN KEY ("hardMuteId") REFERENCES "HardMute" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Subscription"
	ADD CONSTRAINT "Subscription_channelId_fkey" FOREIGN KEY ("channelId") REFERENCES "YoutubeChannel" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

